### ISSUE TITLE
Reject `fetch` from filesystem and localhost

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/zinnia#72]
Zinnia modules must run sandboxed with as little access to the local machine as possible. Ideally, we should limit access to the local network too, but that's out of the scope of this issue.

Let's start by rejecting requests for the following URL kinds and reporting a helpful error to the user:
- `file://` schema
- all loopback ("localhost") hostnames and IPv4 & IPv6 addresses.

**Comment by bajtos** [comment]
Example JS file `fetch-fs.js`:

```js
const res = await fetch('file:///etc/passwd');
console.log('HTTP status', res.status);
if (res.ok) {
  const body = await res.text();
  console.log(body.split(/\n/g)[0]);
}
```

**Deno**

Output of `deno run fetch-fs.js` - Deno asks for permissions:

```
❯ deno run fetch-fs.js
⚠️ ┌ Deno requests read access to "/etc/passwd".
   ├ Requested by `fetch()` API
   ├ Run again with --allow-read to bypass this prompt.
   └ Allow? [y/n] (y = yes, allow; n = no, deny) >
```

After granting the access:

```
❯ deno run fetch-fs.js
✅ Granted read access to "/etc/passwd".
HTTP status 200
##
```

**Zinnia**

Output of `zinnia run fetch-fs.js` - not very helpful.

```
❯ zinnia run fetch-fs.js
error: Uncaught Error: NetworkError when attempting to fetch resource.
    at async mainFetch (internal:ext/fetch/26_fetch.js:267:14)
    at async fetch (internal:ext/fetch/26_fetch.js:491:9)
    at async file:///Users/bajtos/fetch-fs.js:1:13
```
